### ISSUE TITLE
按教程运行了 docs。 为什么显示都是空白呢/

### ISSUE THREAD

**Issue by onestar1** [NeuCharFramework/NcfDocs#19]
![image](https://github.com/NeuCharFramework/NcfDocs/assets/10646303/c3484389-b856-43bf-94d0-0ec6317f3d6e)
![image](https://github.com/NeuCharFramework/NcfDocs/assets/10646303/6b73b5ac-55ee-47a8-b8d6-bdecb0ef2501)

**Comment by JeffreySu** [comment]
@onestar1 请看一下最新的版本。也可以查看线上版本：https://www.ncf.pub/docs/

**Comment by JeffreySu** [comment]
@onestar1 最新版本 V2 已经发布到 main 分支，您可以再试一下，目前已经支持中英文切换。
